targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/src/layer_data/dtos/*.dart
        options:
          field_rename: snake
          create_to_json: false