targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/src/features/**/data/dtos/*.dart
          - lib/src/features/**/data/requests/*.dart
        options:
          field_rename: snake