arb-dir: lib/src/l10n
template-arb-file: app_en.arb
output-dir: lib/src/l10n/generated
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/src/l10n/untranslated.txt
nullable-getter: false